version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: expense-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ExpenseApp@1
      MYSQL_USER: expense
      MYSQL_DATABASE: transactions
      MYSQL_PASSWORD: ExpenseApp@1
    networks:
      - expense
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d

  backend:
    image: backend:1.0
    container_name: expense-backend
    environment:
      - DB_HOST=expense-mysql
    networks:
      - expense

  frontend:
    image: frontend:1.0
    container_name: expense-frontend
    ports:
      - "80:80"
    networks:
      - expense
      
networks:
  expense:
    driver: bridge
